"""Core data schemas for the Verifiable Agent pipeline."""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class RiskType(str, Enum):
    """Risk categories that the Proposer targets."""

    MISSING_EVIDENCE = "missing_evidence"
    MULTI_HOP = "multi_hop"
    PRESSURE_PRESUPPOSITION = "pressure_presupposition"
    UNANSWERABLE = "unanswerable"


class ClaimLabel(str, Enum):
    """Verification label for an atomic claim."""

    SUPPORTED = "S"
    CONTRADICTED = "C"
    NOT_MENTIONED = "N"


class Probe(BaseModel):
    """A safety probe generated by the Proposer."""

    id: str = Field(description="Unique probe identifier")
    question: str = Field(description="The probe question text")
    risk_type: RiskType = Field(description="Targeted risk category")
    ground_truth: Optional[str] = Field(
        default=None, description="Expected answer or evidence reference"
    )
    metadata: dict = Field(default_factory=dict)


class Response(BaseModel):
    """Raw response from the Responder model."""

    probe_id: str
    model_name: str
    text: str
    tokens_used: int = 0
    latency_ms: float = 0.0


class AtomicClaim(BaseModel):
    """A single atomic claim decomposed from a response."""

    id: str
    text: str
    label: Optional[ClaimLabel] = None
    evidence: Optional[str] = Field(
        default=None, description="Evidence snippet used for verification"
    )
    confidence: float = Field(
        default=0.0, ge=0.0, le=1.0, description="Verifier confidence in the label"
    )


class VerificationResult(BaseModel):
    """Full verification output for one probe-response pair."""

    probe: Probe
    response: Response
    claims: list[AtomicClaim] = Field(default_factory=list)
    score: float = Field(default=0.0, description="Response-level aggregated score")
    num_supported: int = 0
    num_contradicted: int = 0
    num_not_mentioned: int = 0


class ExperimentRecord(BaseModel):
    """A complete experiment run record."""

    experiment_id: str
    epoch: int = 0
    model_name: str
    results: list[VerificationResult] = Field(default_factory=list)
    config: dict = Field(default_factory=dict)
    hallucination_rate: float = 0.0
    avg_score: float = 0.0
